In [3]:
# ============================================
# Database to DataFrame: PostgreSQL + Pandas
# ============================================

import pandas as pd
import sqlalchemy
import psycopg2
import psycopg
import adbc_driver_postgresql
import pyarrow

print("pandas      :", pd.__version__)
print("sqlalchemy  :", sqlalchemy.__version__)
print("psycopg2    :", psycopg2.__version__)
print("psycopg     :", psycopg.__version__)
print("pyarrow     :", pyarrow.__version__)
print()
print("✅ All libraries imported successfully!")

pandas      : 3.0.1
sqlalchemy  : 2.0.48
psycopg2    : 2.9.11 (dt dec pq3 ext lo64)
psycopg     : 3.3.3
pyarrow     : 23.0.1

✅ All libraries imported successfully!

In [4]:
# ============================================
# APPROACH 1: Legacy — psycopg2 + SQLAlchemy
# ============================================

from sqlalchemy import create_engine, text

# Create connection engine
# Format: postgresql+psycopg2://username:password@host:port/database
engine = create_engine(
    "postgresql+psycopg2://postgres:postgres@127.0.0.1:5432/sales_db",
    echo=False
)

# Test connection
with engine.connect() as conn:
    result = conn.execute(text("SELECT version()"))
    print("✅ Connected using psycopg2 + SQLAlchemy!")
    print("PostgreSQL version:", result.fetchone()[0])

✅ Connected using psycopg2 + SQLAlchemy!
PostgreSQL version: PostgreSQL 17.9 on x86_64-windows, compiled by msvc-19.44.35223, 64-bit

In [5]:
# Read data using pd.read_sql() — Approach 1
df1 = pd.read_sql(
    sql="SELECT * FROM sales",
    con=engine
)

print("Shape:", df1.shape)
print("\nData Types:\n", df1.dtypes)
print("\nFirst 5 rows:")
df1.head()

Shape: (10, 6)

Data Types:
 id                int64
product_name        str
category            str
quantity          int64
price           float64
sale_date        object
dtype: object

First 5 rows:

   id    product_name     category  quantity    price   sale_date
0   1   Laptop Pro 15  Electronics         3  1299.99  2024-01-15
1   2  Wireless Mouse  Electronics        10    29.99  2024-01-16
2   3    Office Chair    Furniture         2   349.99  2024-01-17
3   4   Standing Desk    Furniture         1   599.99  2024-01-18
4   5     Python Book    Education         5    49.99  2024-01-19

In [6]:
# ============================================
# APPROACH 2: Modern — psycopg3 + SQLAlchemy
# ============================================

# Create engine using psycopg (v3) driver
engine2 = create_engine(
    "postgresql+psycopg://postgres:postgres@127.0.0.1:5432/sales_db",
    echo=False
)

# Test connection
with engine2.connect() as conn:
    result = conn.execute(text("SELECT version()"))
    print("✅ Connected using psycopg3 + SQLAlchemy!")
    print("PostgreSQL version:", result.fetchone()[0])

# Read data using pd.read_sql_query() — more explicit than read_sql()
df2 = pd.read_sql_query(
    sql="SELECT * FROM sales ORDER BY price DESC",
    con=engine2
)

print("\nShape:", df2.shape)
print("\nTop 3 most expensive products:")
df2.head(3)

✅ Connected using psycopg3 + SQLAlchemy!
PostgreSQL version: PostgreSQL 17.9 on x86_64-windows, compiled by msvc-19.44.35223, 64-bit

Shape: (10, 6)

Top 3 most expensive products:

   id    product_name     category  quantity    price   sale_date
0   1   Laptop Pro 15  Electronics         3  1299.99  2024-01-15
1   4   Standing Desk    Furniture         1   599.99  2024-01-18
2   7  Monitor 27inch  Electronics         2   449.99  2024-01-21

In [7]:
# ============================================
# APPROACH 3: Fastest — ADBC Driver
# ============================================
import adbc_driver_postgresql.dbapi as adbc

# ADBC connects directly — no SQLAlchemy needed!
conn3 = adbc.connect(
    "postgresql://postgres:postgres@127.0.0.1:5432/sales_db"
)

print("✅ Connected using ADBC driver!")

# Read data using pd.read_sql() with ADBC connection
df3 = pd.read_sql(
    sql="SELECT * FROM sales",
    con=conn3
)

print("\nShape:", df3.shape)
print("\nData Types:\n", df3.dtypes)
print("\nFirst 5 rows:")
df3.head()

✅ Connected using ADBC driver!

Shape: (10, 6)

Data Types:
 id               int32
product_name       str
category           str
quantity         int32
price           object
sale_date       object
dtype: object

First 5 rows:

   id    product_name     category  quantity    price   sale_date
0   1   Laptop Pro 15  Electronics         3  1299.99  2024-01-15
1   2  Wireless Mouse  Electronics        10    29.99  2024-01-16
2   3    Office Chair    Furniture         2   349.99  2024-01-17
3   4   Standing Desk    Furniture         1   599.99  2024-01-18
4   5     Python Book    Education         5    49.99  2024-01-19

In [8]:
# ============================================
# PHASE 3: PANDAS DATABASE FUNCTIONS
# ============================================

print("=" * 50)
print("1. pd.read_sql() — Auto-detects query vs table")
print("=" * 50)

# Works with both raw SQL and table names
df_auto = pd.read_sql(
    sql="SELECT * FROM sales WHERE category = 'Electronics'",
    con=engine
)
print(f"Electronics products: {len(df_auto)} rows")
print(df_auto[['product_name', 'price']])

==================================================
1. pd.read_sql() — Auto-detects query vs table
==================================================
Electronics products: 5 rows
          product_name    price
0        Laptop Pro 15  1299.99
1       Wireless Mouse    29.99
2  Mechanical Keyboard   129.99
3       Monitor 27inch   449.99
4              USB Hub    39.99

In [9]:
print("=" * 50)
print("2. pd.read_sql_table() — Load entire table")
print("=" * 50)

# read_sql_table() loads a full table — requires SQLAlchemy engine
df_table = pd.read_sql_table(
    table_name="sales",
    con=engine,
    columns=["product_name", "category", "price"]  # select specific columns
)

print(f"Shape: {df_table.shape}")
print("\nAll products:")
print(df_table)

==================================================
2. pd.read_sql_table() — Load entire table
==================================================
Shape: (10, 3)

All products:
          product_name     category    price
0        Laptop Pro 15  Electronics  1299.99
1       Wireless Mouse  Electronics    29.99
2         Office Chair    Furniture   349.99
3        Standing Desk    Furniture   599.99
4          Python Book    Education    49.99
5  Mechanical Keyboard  Electronics   129.99
6       Monitor 27inch  Electronics   449.99
7         Notebook Set   Stationery    12.99
8    Data Science Book    Education    59.99
9              USB Hub  Electronics    39.99

In [10]:
print("=" * 50)
print("3. pd.read_sql_query() — With parameters")
print("=" * 50)

# read_sql_query() — best for complex SQL with filters
df_query = pd.read_sql_query(
    sql="SELECT category, COUNT(*) as total_products, AVG(price) as avg_price, SUM(quantity) as total_units FROM sales GROUP BY category ORDER BY avg_price DESC",
    con=engine
)

print("Sales summary by category:")
print(df_query)

==================================================
3. pd.read_sql_query() — With parameters
==================================================
Sales summary by category:
      category  total_products  avg_price  total_units
0    Furniture               2     474.99            3
1  Electronics               5     389.99           27
2    Education               2      54.99            8
3   Stationery               1      12.99           20

In [11]:
print("=" * 50)
print("4. pd.read_sql_query() — With chunksize")
print("=" * 50)

# chunksize returns an iterator — useful for large datasets
chunks = pd.read_sql_query(
    sql="SELECT * FROM sales",
    con=engine,
    chunksize=3  # read 3 rows at a time
)

all_chunks = []
for i, chunk in enumerate(chunks):
    print(f"Chunk {i+1}: {len(chunk)} rows")
    all_chunks.append(chunk)

# Combine all chunks back into one DataFrame
df_combined = pd.concat(all_chunks, ignore_index=True)
print(f"\nTotal rows after combining: {len(df_combined)}")

==================================================
4. pd.read_sql_query() — With chunksize
==================================================
Chunk 1: 3 rows
Chunk 2: 3 rows
Chunk 3: 3 rows
Chunk 4: 1 rows

Total rows after combining: 10

In [12]:
print("=" * 50)
print("5. pd.DataFrame.to_sql() — Write back to DB")
print("=" * 50)

# Create a new summary DataFrame in Python
df_summary = df_query.copy()
df_summary.columns = ['category', 'total_products', 'avg_price', 'total_units']

# Write DataFrame back to PostgreSQL as a new table
df_summary.to_sql(
    name="sales_summary",        # new table name
    con=engine,
    if_exists="replace",         # replace if already exists
    index=False                  # don't write DataFrame index as a column
)

print("✅ DataFrame written to PostgreSQL as 'sales_summary' table!")

# Verify by reading it back
df_verify = pd.read_sql_table("sales_summary", con=engine)
print("\nVerification — reading back from DB:")
print(df_verify)

==================================================
5. pd.DataFrame.to_sql() — Write back to DB
==================================================
✅ DataFrame written to PostgreSQL as 'sales_summary' table!

Verification — reading back from DB:
      category  total_products  avg_price  total_units
0    Furniture               2     474.99            3
1  Electronics               5     389.99           27
2    Education               2      54.99            8
3   Stationery               1      12.99           20

In [13]:
# ============================================
# FINAL CELL: Approaches Comparison Summary
# ============================================

import time

print("=" * 55)
print("PERFORMANCE COMPARISON — All 3 Approaches")
print("=" * 55)

# Approach 1 — psycopg2 + SQLAlchemy
start = time.time()
df_a1 = pd.read_sql("SELECT * FROM sales", con=engine)
t1 = round(time.time() - start, 4)

# Approach 2 — psycopg3 + SQLAlchemy
start = time.time()
df_a2 = pd.read_sql_query("SELECT * FROM sales", con=engine2)
t2 = round(time.time() - start, 4)

# Approach 3 — ADBC
start = time.time()
df_a3 = pd.read_sql("SELECT * FROM sales", con=conn3)
t3 = round(time.time() - start, 4)

# Summary table
df_comparison = pd.DataFrame({
    "Approach"  : ["Legacy", "Modern", "Fastest"],
    "Driver"    : ["psycopg2", "psycopg3", "ADBC"],
    "SQLAlchemy": ["Yes", "Yes", "No"],
    "Time (s)"  : [t1, t2, t3],
    "Rows"      : [len(df_a1), len(df_a2), len(df_a3)]
})

print(df_comparison.to_string(index=False))
print("\n✅ Assignment Complete! All 3 approaches working!")

# Close ADBC connection
conn3.close()
print("✅ ADBC connection closed cleanly!")

=======================================================
PERFORMANCE COMPARISON — All 3 Approaches
=======================================================
Approach   Driver SQLAlchemy  Time (s)  Rows
  Legacy psycopg2        Yes    0.0048    10
  Modern psycopg3        Yes    0.0038    10
 Fastest     ADBC         No    0.0039    10

✅ Assignment Complete! All 3 approaches working!
✅ ADBC connection closed cleanly!

In [14]:
# ============================================
# PHASE 3 DEEP EXPLORATION — Advanced Parameters
# ============================================

# 1. read_sql_query with parse_dates
df_dates = pd.read_sql_query(
    sql="SELECT * FROM sales",
    con=engine,
    parse_dates=["sale_date"]
)
print("1. parse_dates — sale_date dtype:", df_dates["sale_date"].dtype)

# 2. read_sql_table with index_col
df_indexed = pd.read_sql_table(
    table_name="sales",
    con=engine,
    index_col="id"
)
print("\n2. index_col — index name:", df_indexed.index.name)
print(df_indexed.head(3))

# 3. to_sql with chunksize
df_dates.to_sql(
    name="sales_backup",
    con=engine,
    if_exists="replace",
    index=False,
    chunksize=3
)
print("\n3. to_sql with chunksize=3 — written successfully!")

# 4. to_sql with if_exists='append'
new_row = pd.DataFrame([{
    "product_name": "Gaming Mouse",
    "category": "Electronics",
    "quantity": 5,
    "price": 79.99,
    "sale_date": "2024-01-25"
}])
new_row.to_sql(
    name="sales",
    con=engine,
    if_exists="append",
    index=False
)
print("4. to_sql append — new row added!")

# Verify
df_final = pd.read_sql("SELECT * FROM sales ORDER BY id DESC LIMIT 3", con=engine)
print("\nLast 3 rows in sales table:")
df_final

1. parse_dates — sale_date dtype: datetime64[s]

2. index_col — index name: id
      product_name     category  quantity    price  sale_date
id
1    Laptop Pro 15  Electronics         3  1299.99 2024-01-15
2   Wireless Mouse  Electronics        10    29.99 2024-01-16
3     Office Chair    Furniture         2   349.99 2024-01-17

3. to_sql with chunksize=3 — written successfully!
4. to_sql append — new row added!

Last 3 rows in sales table:

   id       product_name     category  quantity  price   sale_date
0  11       Gaming Mouse  Electronics         5  79.99  2024-01-25
1  10            USB Hub  Electronics         8  39.99  2024-01-24
2   9  Data Science Book    Education         3  59.99  2024-01-23